### ISSUE TITLE
can i change this path?

### ISSUE THREAD

**Issue by quint641** [joaquimguimaraes/chiabot#10]
Hi there, quite new to git. Don't know if this is the right place to ask but when I ./chiabot it's  set to this file path:
FileSystemException: Cannot open file, path = '/root/.chia/mainnet/config/config.yaml' (OS Error: No such file or directory, errno = 2)
is there any way to change this path?

**Comment by joaquimguimaraes** [comment]
Do not run chiabot as root.
Delete the folder you downloaded chiabot and download/run it as a regular user (without sudo)

**Comment by quint641** [comment]
@joaquimguimaraes aah should have done that first instead of asking. Makes sense. Thanks for the quick response!
