### ISSUE TITLE
Can you use wallet address to monitor multiple farmers?

### ISSUE THREAD

**Issue by Tianxinya2021** [joaquimguimaraes/chiabot#13]
Hi, from what I saw chiabot would need to link the farmer.exe, not wallet address. I have a few full node running from different location, ie. independent ip address. It would be helpful to monitor them as they use the same chia address. Can you also make discord independent, ie. standalone? Thanks.

**Comment by joaquimguimaraes** [comment]
They don't need to run under the same ip address. You can run farmer.exe in another full node and link it to your discord account.
Yes, a standalone version is on the works.
