### ISSUE TITLE
Swar's Chia Plot Manager and windows

### ISSUE THREAD

**Issue by digitalkisan** [joaquimguimaraes/chiabot#14]
Is it possible to use this reporting with the windows version in some way, please?
Thank you.

**Comment by joaquimguimaraes** [comment]
Yes it is. If you are using a venv then make sure you run chiabot in that venv

**Comment by digitalkisan** [comment]
> Yes it is. If you are using a venv then make sure you run chiabot in that venv

How would you do that? Just copy the .exe and .JSON file to the same directory?

**Comment by joaquimguimaraes** [comment]
Some people say that works. Or you can activate the venv in cmd and open chiabot with cmd.

**Comment by digitalkisan** [comment]
> Some people say that works. Or you can activate the venv in cmd and open chiabot with cmd.

sorry to be a pain, how would i activate it in venv in cmd. I have worked out how to create a venv for swar but very new to it all. 

Thanks for your help.

**Comment by joaquimguimaraes** [comment]
I feel like this issue would be solved more easily in #chiabot-support channel in Swar's Chia Community, can you ping me there?

**Comment by joaquimguimaraes** [comment]
Issue was solved.
