### ISSUE TITLE
Oh no! Something went wrong 

### ISSUE THREAD

**Issue by fantasiataiwan** [joaquimguimaraes/chiabot#18]
![image](https://user-images.githubusercontent.com/66526700/119874386-1e38d380-bf58-11eb-8923-b53da400de96.png)
I remove this directory few days but this issue appears today

**Comment by joaquimguimaraes** [comment]
Hey, that’s a filesystem error that’s common with network drives on Windows, and I’m afraid there’s not much I can do about it.
There is a simple way you could fix that, make sure you remove that directory \\10.1.1.1.100\Chia from chia’s config.yaml (plot_dests)
Let me know if this works.
