### ISSUE TITLE
unlink command?

### ISSUE THREAD

**Issue by compscidr** [joaquimguimaraes/chiabot#5]
I linked my account to the wrong discord account, and it seems once its linked its not possible to link again to a different discord account. I can confirm the the chia commands work with the wrong account, but with the second account to link it shows that nothing has been linked, even though it says link successful in the bot.

Perhaps an unlink function can be added to the bot to get rid of the association? Or alternatively, perhaps link replaces the old association so you don't need the unlink?

**Comment by joaquimguimaraes** [comment]
Hey, you can generate a new ID by deleting .chiabot_cache.json file and then restarting the client.
Then you may link the new ID.

If linking the same ID again replaced the old association that would allow users to steal other users’ IDs.
An unlink command would be a good idea.
