### ISSUE TITLE
virus detected

### ISSUE THREAD

**Issue by CoderArgentina** [joaquimguimaraes/chiabot#9]
hi, i am downloading the chiabot and windows detects a trojan horse on the farmer.exe file... someone knows what is happening?
![image](https://user-images.githubusercontent.com/83503266/119138447-4be1c200-ba18-11eb-9088-1b12ad120811.png)

**Comment by BOSSitalia** [comment]
^Same issue. Was running fine and then a new update of Windows 10 flagged it through the windows defender

**Comment by joaquimguimaraes** [comment]
chiabot's binaries for windows were falsely flagged as a Trojan by Windows Defender. I have submitted a review to Microsoft and they have removed that detection. It will no longer show if you download chiabot with latest Windows Defender updates.
![image](https://user-images.githubusercontent.com/82336674/119235935-bab03f80-bb2c-11eb-9f41-b4dc8daefd2d.png)
if this does't work for you this is what the Microsoft Analyst had to say:
![image](https://user-images.githubusercontent.com/82336674/119235945-c0a62080-bb2c-11eb-86b7-78d1be3198d9.png)
